gamerule.doInsomnia=false
gamerule.playersNetherPortalDefaultDelay=1
gamerule.spawnChunkRadius=0
gamerule.reducedDebugInfo=true
gamerule.mobExplosionDropDecay=false
gamerule.minecartMaxSpeed=32
gamerule.blockExplosionDropDecay=false
gamerule.globalSoundEvents=false
gamerule.playersSleepingPercentage=143
